version: '3.7'

services:
  app-ui:
    image: ozcey/ecom-ui:v1
    ports:
      - "4200:80"
    restart: always
    depends_on:
      - music-center-app 
    networks:
      - music-center-app-network
     
  music-center-app:
    image: ozcey/ecommerce-api:v1
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - postgres
    environment:
      RDS_HOSTNAME: postgres
      RDS_PORT: 5432
      RDS_DB_NAME: vulApp_db
      RDS_USERNAME: vulApp
      RDS_PASSWORD: Password
    networks:
      - music-center-app-network

  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: vulApp
      POSTGRES_PASSWORD: Password
      POSTGRES_DB: vulApp_db
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - music-center-app-network

volumes:
  postgres-volume:

networks:
  music-center-app-network: